enum BmMiningResource {
    Gold = "gold",
    Bauxite = "bauxite",
    Coal = "coal",
    Oil = "oil",
    CopperOre = "copperore",
    IronOre = "ironore",
    Minerals = "minerals",
    Wood = "wood",
}
type BmCityIcon = `${BmMiningResource}`;

export interface BmCountry {
    id: string;
    visible: boolean;
    areas: number[];
    color: string;
    intId: number;
    name: string;
    population: string;
    landArea: string;
    level: number;
    cities: BmCity[];
}

export interface BmCity {
    id: number;
    name: string;
    population: string;
    latitude: number;
    longitude: number;
    level: number;
    region: string;
    resources: string;
    crops: string;
    icons: BmCityIcon[];
}

export const BM_COUNTRIES_OFF: BmCountry[] = [
    {
        id: "russia",
        visible: true,
        areas: [643],
        color: "#cc3c29",
        intId: 1,
        name: "Российская федерация",
        population: "44.57 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 3,
                name: "Москва",
                population: "9.74 млн.",
                latitude: 55.45,
                longitude: 37.37,
                level: 39,
                region: "Центральная Россия",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["gold"],
            },
            {
                id: 5,
                name: "Санкт-Петербург",
                population: "6.21 млн.",
                latitude: 59.57,
                longitude: 30.19,
                level: 28,
                region: "Центральная Россия",
                resources: "Бокситы, Глина, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["bauxite"],
            },
            {
                id: 6,
                name: "Смоленск",
                population: "4.96 млн.",
                latitude: 54.78,
                longitude: 32.04,
                level: 28,
                region: "Центральная Россия",
                resources: "Глина, Песок, Уголь",
                crops: "Зерно, Картофель, Корм",
                icons: ["coal"],
            },
            {
                id: 8,
                name: "Саратов",
                population: "5.48 млн.",
                latitude: 51.53,
                longitude: 46.03,
                level: 31,
                region: "Южная Россия",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["oil"],
            },
            {
                id: 9,
                name: "Воронеж",
                population: "7.09 млн.",
                latitude: 51.4,
                longitude: 39.12,
                level: 39,
                region: "Южная Россия",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["copperore"],
            },
            {
                id: 11,
                name: "Сочи",
                population: "8.92 млн.",
                latitude: 43.58,
                longitude: 39.72,
                level: 31,
                region: "Южная Россия",
                resources: "Глина, Железная руда, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["ironore"],
            },
            {
                id: 10,
                name: "Волгоград",
                population: "2.17 млн.",
                latitude: 48.41,
                longitude: 44.28,
                level: 26,
                region: "Южная Россия",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["wood"],
            },
        ],
    },
    {
        id: "westerneurope",
        visible: true,
        areas: [250, 56, 528, 276, 756, 442, 470, 438, 832],
        color: "#990a99",
        intId: 36,
        name: "Западная Европа",
        population: "56.57 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 38,
                name: "Париж",
                population: "6.88 млн.",
                latitude: 48.5,
                longitude: 2.2,
                level: 33,
                region: "Франция",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["copperore"],
            },
            {
                id: 41,
                name: "Ницца",
                population: "7.11 млн.",
                latitude: 43.7,
                longitude: 7.26,
                level: 33,
                region: "Франция",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 40,
                name: "Лилль",
                population: "8 млн.",
                latitude: 50.63,
                longitude: 3.03,
                level: 29,
                region: "Франция",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["bauxite"],
            },
            {
                id: 39,
                name: "Лион",
                population: "1.23 млн.",
                latitude: 45.45,
                longitude: 4.5,
                level: 28,
                region: "Франция",
                resources: "Глина, Песок, Уголь",
                crops: "Зерно, Корм, Яблоки",
                icons: ["coal"],
            },
            {
                id: 43,
                name: "Берлин",
                population: "10.39 млн.",
                latitude: 52.31,
                longitude: 13.23,
                level: 41,
                region: "Германия",
                resources: "Глина, Минералы, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["minerals"],
            },
            {
                id: 46,
                name: "Кёльн",
                population: "9.43 млн.",
                latitude: 50.93,
                longitude: 6.93,
                level: 36,
                region: "Германия",
                resources: "Глина, Железная руда, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["ironore"],
            },
            {
                id: 45,
                name: "Нюрнберг",
                population: "13.53 млн.",
                latitude: 49.44,
                longitude: 11.08,
                level: 38,
                region: "Германия",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["gold"],
            },
        ],
    },
    {
        id: "southeurope",
        visible: true,
        areas: [804, 498, 348, 705, 191, 70, 688, 642, 100, 807, 300, 8, 499, 807, -994, 792, 380, 674],
        color: "#cc8e29",
        intId: 25,
        name: "Южная Европа",
        population: "50.63 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 28,
                name: "Стамбул",
                population: "7.99 млн.",
                latitude: 41.01,
                longitude: 28.57,
                level: 33,
                region: "Черноморье",
                resources: "Глина, Песок, Уголь",
                crops: "Виноград, Зерно, Корм",
                icons: ["coal"],
            },
            {
                id: 29,
                name: "Киев",
                population: "7.81 млн.",
                latitude: 50.27,
                longitude: 30.31,
                level: 28,
                region: "Черноморье",
                resources: "Глина, Минералы, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["minerals"],
            },
            {
                id: 30,
                name: "София",
                population: "8.55 млн.",
                latitude: 42.69,
                longitude: 23.31,
                level: 35,
                region: "Черноморье",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 27,
                name: "Одесса",
                population: "3.94 млн.",
                latitude: 46.48,
                longitude: 30.73,
                level: 23,
                region: "Черноморье",
                resources: "Глина, Железная руда, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["ironore"],
            },
            {
                id: 32,
                name: "Рим",
                population: "6.75 млн.",
                latitude: 41.54,
                longitude: 12.3,
                level: 24,
                region: "Адриатика",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["bauxite"],
            },
            {
                id: 34,
                name: "Тирана",
                population: "10.56 млн.",
                latitude: 41.32,
                longitude: 19.81,
                level: 40,
                region: "Адриатика",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["copperore"],
            },
            {
                id: 33,
                name: "Любляна",
                population: "5.02 млн.",
                latitude: 46.05,
                longitude: 14.5,
                level: 29,
                region: "Адриатика",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["oil"],
            },
        ],
    },
    {
        id: "northeurope",
        visible: true,
        areas: [616, 233, 428, 440, 112, 752, 246, 208, 203, 40, 703],
        color: "#83cc29",
        intId: 14,
        name: "Северная Европа",
        population: "32.26 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 16,
                name: "Стокгольм",
                population: "6.17 млн.",
                latitude: 59.32,
                longitude: 18.07,
                level: 31,
                region: "Балтийский",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["oil"],
            },
            {
                id: 19,
                name: "Копенгаген",
                population: "4.68 млн.",
                latitude: 55.68,
                longitude: 12.58,
                level: 23,
                region: "Балтийский",
                resources: "Глина, Песок, Уголь",
                crops: "Зерно, Корм, Яблоки",
                icons: ["coal"],
            },
            {
                id: 17,
                name: "Таллин",
                population: "3.68 млн.",
                latitude: 59.42,
                longitude: 24.74,
                level: 29,
                region: "Балтийский",
                resources: "Глина, Минералы, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["minerals"],
            },
            {
                id: 18,
                name: "Рига",
                population: "1.35 млн.",
                latitude: 56.56,
                longitude: 24.06,
                level: 28,
                region: "Балтийский",
                resources: "Глина, Железная руда, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["ironore"],
            },
            {
                id: 21,
                name: "Минск",
                population: "4.17 млн.",
                latitude: 53.55,
                longitude: 27.33,
                level: 26,
                region: "Центральный",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 22,
                name: "Братислава",
                population: "1.95 млн.",
                latitude: 48.14,
                longitude: 17.1,
                level: 19,
                region: "Центральный",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["gold"],
            },
            {
                id: 24,
                name: "Прага",
                population: "7.44 млн.",
                latitude: 50.08,
                longitude: 14.42,
                level: 28,
                region: "Центральный",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["bauxite"],
            },
            {
                id: 23,
                name: "Варшава",
                population: "2.83 млн.",
                latitude: 52.13,
                longitude: 21.02,
                level: 32,
                region: "Центральный",
                resources: "Глина, Медная руда, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["copperore"],
            },
        ],
    },
    {
        id: "eurasia",
        visible: true,
        areas: [438],
        color: "#83cc29",
        intId: 47,
        name: "Евразия",
        population: "3.27 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 4,
                name: "Нижний Новгород",
                population: "0.79 млн.",
                latitude: 56.18,
                longitude: 43.55,
                level: 29,
                region: "Евразия-конкурс",
                resources: "Глина, Минералы, Песок",
                crops: "Зерно, Корм",
                icons: ["minerals"],
            },
            {
                id: 44,
                name: "Ганновер",
                population: "0.79 млн.",
                latitude: 52.37,
                longitude: 9.72,
                level: 29,
                region: "Евразия-конкурс",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["oil"],
            },
            {
                id: 35,
                name: "Афины",
                population: "0.79 млн.",
                latitude: 37.97,
                longitude: 23.73,
                level: 29,
                region: "Евразия-конкурс",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["gold"],
            },
            {
                id: 13,
                name: "Калининград",
                population: "0.90 млн.",
                latitude: 54.43,
                longitude: 20.3,
                level: 1,
                region: "Калининградская область",
                resources:
                    "Бокситы, Глина, Древесина, Железная руда, Золото, Медная руда, Минералы, Нефть, Песок, Уголь",
                crops: "Виноград, Зерно, Какао, Картофель, Корм, Свекла, Тропические фрукты, Яблоки",
                icons: [],
            },
        ],
    },
];
