enum BmMiningResource {
    Gold = "gold",
    Bauxite = "bauxite",
    Coal = "coal",
    Oil = "oil",
    CopperOre = "copperore",
    IronOre = "ironore",
    Minerals = "minerals",
    Wood = "wood",
}
type BmCityIcon = `${BmMiningResource}`;

export interface BmCountry {
    id: string;
    visible: boolean;
    areas: number[];
    color: string;
    intId: number;
    name: string;
    population: string;
    landArea: string;
    level: number;
    cities: BmCity[];
}

export interface BmCity {
    id: number;
    name: string;
    population: string;
    latitude: number;
    longitude: number;
    level: number;
    region: string;
    resources: string;
    crops: string;
    icons: BmCityIcon[];
}

export const BM_COUNTRIES: BmCountry[] = [
    {
        id: "russia",
        visible: true,
        areas: [643],
        color: "#cc3c29",
        intId: 1,
        name: "Российская федерация",
        population: "31.75 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 3,
                name: "Москва",
                population: "6.29 млн.",
                latitude: 55.45,
                longitude: 37.37,
                level: 34,
                region: "Центральная Россия",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["gold"],
            },
            {
                id: 5,
                name: "Санкт-Петербург",
                population: "4.46 млн.",
                latitude: 59.57,
                longitude: 30.19,
                level: 23,
                region: "Центральная Россия",
                resources: "Бокситы, Глина, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["bauxite"],
            },
            {
                id: 6,
                name: "Смоленск",
                population: "3.41 млн.",
                latitude: 54.78,
                longitude: 32.04,
                level: 22,
                region: "Центральная Россия",
                resources: "Глина, Песок, Уголь",
                crops: "Зерно, Картофель, Корм",
                icons: ["coal"],
            },
            {
                id: 8,
                name: "Саратов",
                population: "4.70 млн.",
                latitude: 51.53,
                longitude: 46.03,
                level: 26,
                region: "Южная Россия",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["oil"],
            },
            {
                id: 9,
                name: "Воронеж",
                population: "5.65 млн.",
                latitude: 51.4,
                longitude: 39.12,
                level: 34,
                region: "Южная Россия",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["copperore"],
            },
            {
                id: 11,
                name: "Сочи",
                population: "7.23 млн.",
                latitude: 43.58,
                longitude: 39.72,
                level: 27,
                region: "Южная Россия",
                resources: "Глина, Железная руда, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["ironore"],
            },
        ],
    },
    {
        id: "westerneurope",
        visible: true,
        areas: [250, 56, 528, 276, 756, 442, 470, 438, 832],
        color: "#990a99",
        intId: 36,
        name: "Западная Европа",
        population: "32.86 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 38,
                name: "Париж",
                population: "4.65 млн.",
                latitude: 48.5,
                longitude: 2.2,
                level: 28,
                region: "Франция",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["copperore"],
            },
            {
                id: 41,
                name: "Ницца",
                population: "4.28 млн.",
                latitude: 43.7,
                longitude: 7.26,
                level: 26,
                region: "Франция",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 40,
                name: "Лилль",
                population: "3.81 млн.",
                latitude: 50.63,
                longitude: 3.03,
                level: 23,
                region: "Франция",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["bauxite"],
            },
            {
                id: 43,
                name: "Берлин",
                population: "6.90 млн.",
                latitude: 52.31,
                longitude: 13.23,
                level: 36,
                region: "Германия",
                resources: "Глина, Минералы, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["minerals"],
            },
            {
                id: 46,
                name: "Кёльн",
                population: "6.66 млн.",
                latitude: 50.93,
                longitude: 6.93,
                level: 31,
                region: "Германия",
                resources: "Глина, Железная руда, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["ironore"],
            },
            {
                id: 45,
                name: "Нюрнберг",
                population: "6.57 млн.",
                latitude: 49.44,
                longitude: 11.08,
                level: 30,
                region: "Германия",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["gold"],
            },
        ],
    },
    {
        id: "southeurope",
        visible: true,
        areas: [804, 498, 348, 705, 191, 70, 688, 642, 100, 807, 300, 8, 499, 807, -994, 792, 380, 674],
        color: "#cc8e29",
        intId: 25,
        name: "Южная Европа",
        population: "37.70 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 28,
                name: "Стамбул",
                population: "5.98 млн.",
                latitude: 41.01,
                longitude: 28.57,
                level: 28,
                region: "Черноморье",
                resources: "Глина, Песок, Уголь",
                crops: "Виноград, Зерно, Корм",
                icons: ["coal"],
            },
            {
                id: 29,
                name: "Киев",
                population: "5.66 млн.",
                latitude: 50.27,
                longitude: 30.31,
                level: 25,
                region: "Черноморье",
                resources: "Глина, Минералы, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["minerals"],
            },
            {
                id: 30,
                name: "София",
                population: "5.36 млн.",
                latitude: 42.69,
                longitude: 23.31,
                level: 28,
                region: "Черноморье",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 27,
                name: "Одесса",
                population: "3.17 млн.",
                latitude: 46.48,
                longitude: 30.73,
                level: 19,
                region: "Черноморье",
                resources: "Глина, Железная руда, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["ironore"],
            },
            {
                id: 32,
                name: "Рим",
                population: "5.74 млн.",
                latitude: 41.54,
                longitude: 12.3,
                level: 21,
                region: "Адриатика",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["bauxite"],
            },
            {
                id: 34,
                name: "Тирана",
                population: "7.93 млн.",
                latitude: 41.32,
                longitude: 19.81,
                level: 34,
                region: "Адриатика",
                resources: "Глина, Медная руда, Песок",
                crops: "Зерно, Корм, Яблоки",
                icons: ["copperore"],
            },
            {
                id: 33,
                name: "Любляна",
                population: "3.87 млн.",
                latitude: 46.05,
                longitude: 14.5,
                level: 25,
                region: "Адриатика",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["oil"],
            },
        ],
    },
    {
        id: "northeurope",
        visible: true,
        areas: [616, 233, 428, 440, 112, 752, 246, 208, 203, 40, 703],
        color: "#83cc29",
        intId: 14,
        name: "Северная Европа",
        population: "25.15 млн.",
        landArea: "0.0",
        level: 0,
        cities: [
            {
                id: 16,
                name: "Стокгольм",
                population: "5.06 млн.",
                latitude: 59.32,
                longitude: 18.07,
                level: 26,
                region: "Балтийский",
                resources: "Глина, Нефть, Песок",
                crops: "Зерно, Какао, Корм",
                icons: ["oil"],
            },
            {
                id: 19,
                name: "Копенгаген",
                population: "4.16 млн.",
                latitude: 55.68,
                longitude: 12.58,
                level: 20,
                region: "Балтийский",
                resources: "Глина, Песок, Уголь",
                crops: "Зерно, Корм, Яблоки",
                icons: ["coal"],
            },
            {
                id: 17,
                name: "Таллин",
                population: "3.12 млн.",
                latitude: 59.42,
                longitude: 24.74,
                level: 23,
                region: "Балтийский",
                resources: "Глина, Минералы, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["minerals"],
            },
            {
                id: 21,
                name: "Минск",
                population: "3.53 млн.",
                latitude: 53.55,
                longitude: 27.33,
                level: 21,
                region: "Центральный",
                resources: "Глина, Древесина, Песок",
                crops: "Зерно, Корм, Свекла",
                icons: ["wood"],
            },
            {
                id: 22,
                name: "Братислава",
                population: "1.88 млн.",
                latitude: 48.14,
                longitude: 17.1,
                level: 15,
                region: "Центральный",
                resources: "Глина, Золото, Песок",
                crops: "Зерно, Картофель, Корм",
                icons: ["gold"],
            },
            {
                id: 24,
                name: "Прага",
                population: "5.19 млн.",
                latitude: 50.08,
                longitude: 14.42,
                level: 23,
                region: "Центральный",
                resources: "Бокситы, Глина, Песок",
                crops: "Зерно, Корм, Тропические фрукты",
                icons: ["bauxite"],
            },
            {
                id: 23,
                name: "Варшава",
                population: "2.20 млн.",
                latitude: 52.13,
                longitude: 21.02,
                level: 21,
                region: "Центральный",
                resources: "Глина, Медная руда, Песок",
                crops: "Виноград, Зерно, Корм",
                icons: ["copperore"],
            },
        ],
    },
];
