export const BM_CATEGORIES = [
    { id: 19, title: "Автомобильные товары" },
    { id: 9, title: "Животные" },
    { id: 3, title: "Компоненты" },
    { id: 2, title: "Материалы" },
    { id: 18, title: "Одежда и обувь" },
    { id: 1, title: "Полезные ископаемые" },
    { id: 20, title: "Предметы роскоши" },
    { id: 5, title: "Продукты питания" },
    { id: 8, title: "Промышленное товары" },
    { id: 4, title: "Сельскохозяйственная продукция" },
    { id: 17, title: "Спорттовары" },
    { id: 7, title: "Строительные материалы" },
    { id: 6, title: "Товары народного потребления" },
    { id: 16, title: "Фармацевтика" },
    { id: 11, title: "Электроника" },
];

export const BM_CATEGORIES_RETAIL = [...BM_CATEGORIES, { id: 99, title: "Рестораны" }];

export const BM_PRODUCTS = [
    { id: 159, type: "car", title: "Автомобиль", categoryId: 19 },
    { id: 375, type: "battery", title: "Аккумулятор", categoryId: 19 },
    { id: 398, type: "accessories", title: "Аксессуары", categoryId: 19 },
    { id: 399, type: "jack", title: "Домкрат", categoryId: 19 },
    { id: 383, type: "quadbike", title: "Квадроцикл", categoryId: 19 },
    { id: 315, type: "compressor", title: "Компрессор", categoryId: 19 },
    { id: 376, type: "bodyparts", title: "Кузовные детали", categoryId: 19 },
    { id: 236, type: "machineoil", title: "Машинное масло", categoryId: 19 },
    { id: 401, type: "motoblock", title: "Мотоблок", categoryId: 19 },
    { id: 160, type: "moto", title: "Мотоцикл", categoryId: 19 },
    { id: 314, type: "washerfluid", title: "Омывающая жидкость", categoryId: 19 },
    { id: 400, type: "subwoofer", title: "Сабвуфер", categoryId: 19 },
    { id: 346, type: "scooter", title: "Скутер", categoryId: 19 },
    { id: 161, type: "tire", title: "Шины", categoryId: 19 },
    { id: 378, type: "electriccar", title: "Электромобиль", categoryId: 19 },
    //
    { id: 187, type: "cow", title: "Коровы", categoryId: 9 },
    { id: 189, type: "hen", title: "Куры", categoryId: 9 },
    { id: 190, type: "sheep", title: "Овцы", categoryId: 9 },
    { id: 188, type: "pig", title: "Свиньи", categoryId: 9 },
    { id: 247, type: "sable", title: "Соболь", categoryId: 9 },
    //
    { id: 43, type: "engine", title: "Двигатель", categoryId: 3 },
    { id: 369, type: "display", title: "Дисплей", categoryId: 3 },
    { id: 44, type: "parts", title: "Комплектующие", categoryId: 3 },
    { id: 370, type: "wires", title: "Провода", categoryId: 3 },
    { id: 45, type: "chips", title: "Электронные компоненты", categoryId: 3 },
    //
    { id: 15, type: "aluminium", title: "Алюминий", categoryId: 2 },
    { id: 30, type: "aromatisator", title: "Ароматизатор", categoryId: 2 },
    { id: 17, type: "paper", title: "Бумага", categoryId: 2 },
    { id: 38, type: "dieselfuel", title: "Дизельное топливо", categoryId: 2 },
    { id: 26, type: "acid", title: "Кислота", categoryId: 2 },
    { id: 18, type: "leather", title: "Кожа", categoryId: 2 },
    { id: 16, type: "silicon", title: "Кремний", categoryId: 2 },
    { id: 367, type: "copper", title: "Медь", categoryId: 2 },
    { id: 19, type: "plastic", title: "Пластик", categoryId: 2 },
    { id: 29, type: "reagent", title: "Реактивы", categoryId: 2 },
    { id: 20, type: "rubber", title: "Резина", categoryId: 2 },
    { id: 22, type: "synthetics", title: "Синтетика", categoryId: 2 },
    { id: 28, type: "spirits", title: "Спирт", categoryId: 2 },
    { id: 23, type: "steel", title: "Сталь", categoryId: 2 },
    { id: 24, type: "glass", title: "Стекло", categoryId: 2 },
    { id: 21, type: "fabric", title: "Ткань", categoryId: 2 },
    { id: 33, type: "fertilizer", title: "Удобрения", categoryId: 2 },
    { id: 31, type: "wool", title: "Шерсть", categoryId: 2 },
    //
    { id: 207, type: "blouse", title: "Блузка", categoryId: 18 },
    { id: 139, type: "childshoes", title: "Детская обувь", categoryId: 18 },
    { id: 144, type: "childclothes", title: "Детская одежда", categoryId: 18 },
    { id: 396, type: "jeans", title: "Джинсы", categoryId: 18 },
    { id: 138, type: "womanshoes", title: "Женская обувь", categoryId: 18 },
    { id: 204, type: "suit", title: "Костюм", categoryId: 18 },
    { id: 203, type: "jacket", title: "Куртка", categoryId: 18 },
    { id: 137, type: "manshoes", title: "Мужская обувь", categoryId: 18 },
    { id: 326, type: "socks", title: "Носки", categoryId: 18 },
    { id: 206, type: "mancoat", title: "Пальто", categoryId: 18 },
    { id: 149, type: "gloves", title: "Перчатки", categoryId: 18 },
    { id: 208, type: "dress", title: "Платье", categoryId: 18 },
    { id: 148, type: "belt", title: "Ремень", categoryId: 18 },
    { id: 205, type: "shirt", title: "Рубашка", categoryId: 18 },
    { id: 140, type: "sportshoes", title: "Спортивная обувь", categoryId: 18 },
    { id: 145, type: "sportclothes", title: "Спортивная одежда", categoryId: 18 },
    { id: 147, type: "bag", title: "Сумка", categoryId: 18 },
    { id: 395, type: "tshirt", title: "Футболка", categoryId: 18 },
    { id: 397, type: "cap", title: "Шапка", categoryId: 18 },
    { id: 210, type: "furcoat", title: "Шуба", categoryId: 18 },
    //
    { id: 3, type: "bauxite", title: "Бокситы", categoryId: 1 },
    { id: 4, type: "clay", title: "Глина", categoryId: 1 },
    { id: 5, type: "wood", title: "Древесина", categoryId: 1 },
    { id: 6, type: "ironore", title: "Железная руда", categoryId: 1 },
    { id: 7, type: "gold", title: "Золото", categoryId: 1 },
    { id: 366, type: "copperore", title: "Медная руда", categoryId: 1 },
    { id: 311, type: "minerals", title: "Минералы", categoryId: 1 },
    { id: 1, type: "oil", title: "Нефть", categoryId: 1 },
    { id: 9, type: "sand", title: "Песок", categoryId: 1 },
    { id: 14, type: "coal", title: "Уголь", categoryId: 1 },
    //
    { id: 209, type: "underwear", title: "Белье", categoryId: 20 },
    { id: 321, type: "bijouterie", title: "Бижутерия", categoryId: 20 },
    { id: 325, type: "razor", title: "Бритва", categoryId: 20 },
    { id: 152, type: "watches", title: "Золотые часы", categoryId: 20 },
    { id: 405, type: "tights", title: "Колготки", categoryId: 20 },
    { id: 382, type: "makeup", title: "Косметика", categoryId: 20 },
    { id: 170, type: "parfume", title: "Парфюмерия", categoryId: 20 },
    { id: 322, type: "sunglasses", title: "Солнечные очки", categoryId: 20 },
    { id: 347, type: "souvenir", title: "Сувенир", categoryId: 20 },
    { id: 403, type: "hairdryer", title: "Фен", categoryId: 20 },
    { id: 402, type: "flowers", title: "Цветы", categoryId: 20 },
    { id: 404, type: "epilator", title: "Эпилятор", categoryId: 20 },
    { id: 166, type: "jewelry", title: "Ювелирные украшения", categoryId: 20 },
    //
    { id: 90, type: "wine", title: "Вино", categoryId: 5 },
    { id: 84, type: "yogurt", title: "Йогурт", categoryId: 5 },
    { id: 78, type: "sausages", title: "Колбаса", categoryId: 5 },
    { id: 92, type: "vodka", title: "Крепкий алкоголь", categoryId: 5 },
    { id: 87, type: "croup", title: "Крупа", categoryId: 5 },
    { id: 80, type: "macaron", title: "Макаронные изделия", categoryId: 5 },
    { id: 238, type: "butter", title: "Масло", categoryId: 5 },
    { id: 86, type: "flour", title: "Мука", categoryId: 5 },
    { id: 101, type: "cookies", title: "Печенье", categoryId: 5 },
    { id: 89, type: "beer", title: "Пиво", categoryId: 5 },
    { id: 94, type: "gaswater", title: "Прохладительные напитки", categoryId: 5 },
    { id: 50, type: "fat", title: "Растительное масло", categoryId: 5 },
    { id: 57, type: "sugar", title: "Сахар", categoryId: 5 },
    { id: 95, type: "juice", title: "Сок", categoryId: 5 },
    { id: 83, type: "cheese", title: "Сыр", categoryId: 5 },
    { id: 102, type: "cake", title: "Торт", categoryId: 5 },
    { id: 99, type: "bread", title: "Хлеб", categoryId: 5 },
    { id: 103, type: "chocolate", title: "Шоколад", categoryId: 5 },
    //
    { id: 181, type: "autoloader", title: "Автопогрузчик", categoryId: 8 },
    { id: 394, type: "windgenerator", title: "Ветрогенератор", categoryId: 8 },
    { id: 184, type: "mineeq", title: "Горное оборудование", categoryId: 8 },
    { id: 327, type: "truck", title: "Грузовик", categoryId: 8 },
    { id: 182, type: "crane", title: "Кран", categoryId: 8 },
    { id: 176, type: "device", title: "Прибор", categoryId: 8 },
    { id: 178, type: "machineline", title: "Производственная линия", categoryId: 8 },
    { id: 177, type: "machine", title: "Станки", categoryId: 8 },
    { id: 185, type: "tractor", title: "Трактор", categoryId: 8 },
    { id: 243, type: "heavyeq", title: "Тяжелое оборудование", categoryId: 8 },
    //
    { id: 251, type: "grape", title: "Виноград", categoryId: 4 },
    { id: 46, type: "grain", title: "Зерно", categoryId: 4 },
    { id: 47, type: "cacao", title: "Какао", categoryId: 4 },
    { id: 255, type: "potato", title: "Картофель", categoryId: 4 },
    { id: 73, type: "biofeed", title: "Корм", categoryId: 4 },
    { id: 237, type: "fur", title: "Мех", categoryId: 4 },
    { id: 49, type: "milk", title: "Молоко", categoryId: 4 },
    { id: 51, type: "meat", title: "Мясо", categoryId: 4 },
    { id: 313, type: "vegetables", title: "Овощи", categoryId: 4 },
    { id: 56, type: "fish", title: "Рыба", categoryId: 4 },
    { id: 260, type: "beet", title: "Свекла", categoryId: 4 },
    { id: 312, type: "fruits", title: "Тропические фрукты", categoryId: 4 },
    { id: 250, type: "apples", title: "Яблоки", categoryId: 4 },
    { id: 72, type: "eggs", title: "Яйца", categoryId: 4 },
    //
    { id: 120, type: "bicycle", title: "Велосипед", categoryId: 17 },
    { id: 350, type: "dumbbells", title: "Гантели", categoryId: 17 },
    { id: 414, type: "rug", title: "Коврик", categoryId: 17 },
    { id: 351, type: "compression", title: "Компрессионная одежда", categoryId: 17 },
    { id: 361, type: "skates", title: "Коньки", categoryId: 17 },
    { id: 362, type: "skiing", title: "Лыжи", categoryId: 17 },
    { id: 363, type: "ball", title: "Мяч", categoryId: 17 },
    { id: 357, type: "mattress", title: "Надувной матрас", categoryId: 17 },
    { id: 352, type: "tent", title: "Палатка", categoryId: 17 },
    { id: 364, type: "rackets", title: "Ракетки", categoryId: 17 },
    { id: 355, type: "rubberboat", title: "Резиновая лодка", categoryId: 17 },
    { id: 359, type: "roller", title: "Роликовые коньки", categoryId: 17 },
    { id: 354, type: "backpack", title: "Рюкзак", categoryId: 17 },
    { id: 360, type: "kickscooter", title: "Самокат", categoryId: 17 },
    { id: 353, type: "sleeping", title: "Спальный мешок", categoryId: 17 },
    { id: 415, type: "thermos", title: "Термос", categoryId: 17 },
    { id: 356, type: "axe", title: "Топор", categoryId: 17 },
    { id: 349, type: "training", title: "Тренажер", categoryId: 17 },
    { id: 413, type: "flashlight", title: "Фонарь", categoryId: 17 },
    { id: 406, type: "helmet", title: "Шлем", categoryId: 17 },
    //
    { id: 244, type: "tools", title: "Инструменты", categoryId: 7 },
    { id: 173, type: "concrete", title: "Бетонный блок", categoryId: 7 },
    { id: 323, type: "door", title: "Дверь", categoryId: 7 },
    { id: 324, type: "tile", title: "Керамическая плитка", categoryId: 7 },
    { id: 172, type: "brick", title: "Кирпич", categoryId: 7 },
    { id: 348, type: "glue", title: "Клей", categoryId: 7 },
    { id: 32, type: "paint", title: "Краска", categoryId: 7 },
    { id: 419, type: "fasteners", title: "Крепеж", categoryId: 7 },
    { id: 240, type: "floor", title: "Напольные покрытия", categoryId: 7 },
    { id: 407, type: "heater", title: "Обогреватель", categoryId: 7 },
    { id: 239, type: "wallpaper", title: "Обои", categoryId: 7 },
    { id: 249, type: "window", title: "Окна", categoryId: 7 },
    { id: 242, type: "sanitary", title: "Сантехника", categoryId: 7 },
    { id: 241, type: "lamp", title: "Светильник", categoryId: 7 },
    { id: 411, type: "pipes", title: "Трубы", categoryId: 7 },
    { id: 174, type: "cement", title: "Цемент", categoryId: 7 },
    { id: 412, type: "curtains", title: "Шторы", categoryId: 7 },
    //
    { id: 150, type: "umbrella", title: "Зонт", categoryId: 6 },
    { id: 108, type: "toothpaste", title: "Зубная паста", categoryId: 6 },
    { id: 121, type: "toys", title: "Игрушки", categoryId: 6 },
    { id: 377, type: "constructor", title: "Конструктор", categoryId: 6 },
    { id: 132, type: "chair", title: "Кресло", categoryId: 6 },
    { id: 135, type: "bed", title: "Кровать", categoryId: 6 },
    { id: 408, type: "kitchen", title: "Кухонный гарнитур", categoryId: 6 },
    { id: 107, type: "detergent", title: "Моющее средство", categoryId: 6 },
    { id: 105, type: "soap", title: "Мыло", categoryId: 6 },
    { id: 131, type: "sofa", title: "Мягкая мебель", categoryId: 6 },
    { id: 319, type: "beddress", title: "Постельные принадлежности", categoryId: 6 },
    { id: 153, type: "dishes", title: "Посуда", categoryId: 6 },
    { id: 373, type: "cleaner", title: "Пылесос", categoryId: 6 },
    { id: 158, type: "pan", title: "Сковорода", categoryId: 6 },
    { id: 106, type: "soappowder", title: "Стиральный порошок", categoryId: 6 },
    { id: 134, type: "table", title: "Стол", categoryId: 6 },
    { id: 420, type: "stool", title: "Стул", categoryId: 6 },
    { id: 320, type: "teapot", title: "Чайник", categoryId: 6 },
    { id: 133, type: "wardrobe", title: "Шкаф", categoryId: 6 },
    //
    { id: 344, type: "antibiotics", title: "Антибиотики", categoryId: 16 },
    { id: 416, type: "antiseptic", title: "Антисептик", categoryId: 16 },
    { id: 334, type: "supplements", title: "БАД", categoryId: 16 },
    { id: 343, type: "vaccine", title: "Вакцина", categoryId: 16 },
    { id: 333, type: "vitamins", title: "Витамины", categoryId: 16 },
    { id: 417, type: "babyfood", title: "Детская смесь", categoryId: 16 },
    { id: 337, type: "contraceptives", title: "Контрацептивы", categoryId: 16 },
    { id: 330, type: "herbs", title: "Лекарственные травы", categoryId: 16 },
    { id: 384, type: "healingcream", title: "Лечебный крем", categoryId: 16 },
    { id: 339, type: "medtechnic", title: "Мед техника", categoryId: 16 },
    { id: 331, type: "microculture", title: "Микроорганическая культура", categoryId: 16 },
    { id: 336, type: "tincture", title: "Настойка", categoryId: 16 },
    { id: 340, type: "orthopedic", title: "Ортопедические изделия", categoryId: 16 },
    { id: 338, type: "bandage", title: "Перевязочные средства", categoryId: 16 },
    { id: 342, type: "cough", title: "Противопростудные", categoryId: 16 },
    { id: 341, type: "prescription", title: "Рецептурные препараты", categoryId: 16 },
    { id: 418, type: "herbal", title: "Травяной сбор", categoryId: 16 },
    { id: 332, type: "substance", title: "Фармацевтическая субстанция", categoryId: 16 },
    //
    { id: 117, type: "audio", title: "Аудиотехника", categoryId: 11 },
    { id: 409, type: "hob", title: "Варочная панель", categoryId: 11 },
    { id: 410, type: "hood", title: "Вытяжка", categoryId: 11 },
    { id: 318, type: "xbox", title: "Игровая приставка", categoryId: 11 },
    { id: 374, type: "conditioning", title: "Кондиционер", categoryId: 11 },
    { id: 381, type: "foodprocessor", title: "Кухонный комбайн", categoryId: 11 },
    { id: 316, type: "microwave", title: "Микроволновка", categoryId: 11 },
    { id: 129, type: "mobile", title: "Мобильный телефон", categoryId: 11 },
    { id: 125, type: "computer", title: "Настольный компьютер", categoryId: 11 },
    { id: 371, type: "headphones", title: "Наушники", categoryId: 11 },
    { id: 126, type: "notebook", title: "Ноутбук", categoryId: 11 },
    { id: 317, type: "tablet", title: "Планшет", categoryId: 11 },
    { id: 112, type: "dishwasher", title: "Посудомоечная машина", categoryId: 11 },
    { id: 128, type: "printer", title: "Принтер", categoryId: 11 },
    { id: 372, type: "smartwatch", title: "Смарт часы", categoryId: 11 },
    { id: 111, type: "washer", title: "Стиральная машина", categoryId: 11 },
    { id: 115, type: "tv", title: "Телевизор", categoryId: 11 },
    { id: 113, type: "iron", title: "Утюг", categoryId: 11 },
    { id: 151, type: "photo", title: "Фотоаппарат", categoryId: 11 },
    { id: 110, type: "refrigirator", title: "Холодильник", categoryId: 11 },
    //
    { id: 261, type: "energy", title: "Электроэнергия", categoryId: 12 },
];

export const BM_PRODUCTS_RETAIL = [
    ...BM_PRODUCTS,
    { id: 275, title: "Борщ", type: "borcht", categoryId: 99 },
    {
        id: 294,
        title: "Винегрет",
        categoryId: 99,
        type: "venigret",
    },
    {
        id: 296,
        title: "Гамбургер",
        categoryId: 99,
        type: "hamburger",
    },
    {
        id: 392,
        title: "Глинтвейн",
        categoryId: 99,
        type: "alkococteil",
    },
    {
        id: 286,
        title: "Жареная рыба",
        categoryId: 99,
        type: "friedfish",
    },
    {
        id: 389,
        title: "Запеканка",
        categoryId: 99,
        type: "frenchfries",
    },
    {
        id: 385,
        title: "Итальянское ассорти",
        categoryId: 99,
        type: "potatomeat",
    },
    {
        id: 393,
        title: "Молочный коктейль",
        categoryId: 99,
        type: "juicecocteil",
    },
    {
        id: 283,
        title: "Мясо по-французски",
        categoryId: 99,
        type: "frenchmeat",
    },
    {
        id: 390,
        title: "Пивной сет",
        categoryId: 99,
        type: "nuggets",
    },
    {
        id: 298,
        title: "Пицца",
        categoryId: 99,
        type: "pizza",
    },
    {
        id: 284,
        title: "Плов",
        categoryId: 99,
        type: "pilaf",
    },
    {
        id: 386,
        title: "Ребрышки по-фламандски",
        categoryId: 99,
        type: "ase",
    },
    {
        id: 293,
        title: "Салат Греческий",
        categoryId: 99,
        type: "saladgreece",
    },
    {
        id: 290,
        title: "Салат Столичный",
        categoryId: 99,
        type: "saladcapital",
    },
    {
        id: 388,
        title: "Сельдь под шубой",
        categoryId: 99,
        type: "saladceasar",
    },
    {
        id: 391,
        title: "Сидр",
        categoryId: 99,
        type: "compote",
    },
    {
        id: 276,
        title: "Солянка",
        categoryId: 99,
        type: "saltwort",
    },
    {
        id: 302,
        title: "Шаурма",
        categoryId: 99,
        type: "shawarma",
    },
    {
        id: 387,
        title: "Штрудель",
        categoryId: 99,
        type: "schnitzel",
    },
];

export type BmCategory = (typeof BM_CATEGORIES)[number];
export type BmProduct = (typeof BM_PRODUCTS)[number];
export type BmCategoryProducts = {
    category: BmCategory;
    products: BmProduct[];
};

export const BM_CATEGORY_PRODUCTS = BM_CATEGORIES.reduce((acc, category) => {
    const products = BM_PRODUCTS.filter(product => product.categoryId === category.id);
    acc.push({ category, products });
    return acc;
}, [] as BmCategoryProducts[]);

export const BM_CATEGORY_RETAIL_PRODUCTS = BM_CATEGORIES_RETAIL.reduce((acc, category) => {
    const products = BM_PRODUCTS_RETAIL.filter(product => product.categoryId === category.id);
    acc.push({ category, products });
    return acc;
}, [] as BmCategoryProducts[]);
