export interface BmRoad {
    id: number;
    type: string;
    from: number;
    to: number;
    hint: string;
    weight: number;
    color: string;
    points: string;
    olimpic: boolean;
}

export const BM_ROADS: BmRoad[] = [
    {
        id: 2,
        type: "auto",
        from: 6,
        to: 5,
        hint: "<b>Дорога</b><br/>Смоленск-Санкт-Петербург<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 3,
        type: "auto",
        from: 3,
        to: 5,
        hint: "<b>Дорога</b><br/>Москва-Санкт-Петербург<br/><br/>Качество: 0.965",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 5,
        type: "auto",
        from: 17,
        to: 5,
        hint: "<b>Дорога</b><br/>Таллин-Санкт-Петербург<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 8,
        type: "auto",
        from: 3,
        to: 8,
        hint: "<b>Дорога</b><br/>Москва-Саратов<br/><br/>Качество: 0.965",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 9,
        type: "auto",
        from: 9,
        to: 8,
        hint: "<b>Дорога</b><br/>Воронеж-Саратов<br/><br/>Качество: 0.96",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 13,
        type: "auto",
        from: 9,
        to: 11,
        hint: "<b>Дорога</b><br/>Воронеж-Сочи<br/><br/>Качество: 0.98",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 14,
        type: "auto",
        from: 27,
        to: 11,
        hint: "<b>Дорога</b><br/>Одесса-Сочи<br/><br/>Качество: 0.97",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 15,
        type: "auto",
        from: 28,
        to: 11,
        hint: "<b>Дорога</b><br/>Стамбул-Сочи<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 16,
        type: "auto",
        from: 27,
        to: 28,
        hint: "<b>Дорога</b><br/>Одесса-Стамбул<br/><br/>Качество: 0.99",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 17,
        type: "auto",
        from: 30,
        to: 28,
        hint: "<b>Дорога</b><br/>София-Стамбул<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 18,
        type: "auto",
        from: 34,
        to: 28,
        hint: "<b>Дорога</b><br/>Тирана-Стамбул<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 22,
        type: "auto",
        from: 34,
        to: 32,
        hint: "<b>Дорога</b><br/>Тирана-Рим<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 24,
        type: "auto",
        from: 33,
        to: 32,
        hint: "<b>Дорога</b><br/>Любляна-Рим<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 25,
        type: "auto",
        from: 41,
        to: 32,
        hint: "<b>Дорога</b><br/>Ницца-Рим<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 26,
        type: "auto",
        from: 33,
        to: 41,
        hint: "<b>Дорога</b><br/>Любляна-Ницца<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 27,
        type: "auto",
        from: 45,
        to: 41,
        hint: "<b>Дорога</b><br/>Нюрнберг-Ницца<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 32,
        type: "auto",
        from: 46,
        to: 38,
        hint: "<b>Дорога</b><br/>Кёльн-Париж<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 33,
        type: "auto",
        from: 40,
        to: 38,
        hint: "<b>Дорога</b><br/>Лилль-Париж<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 34,
        type: "auto",
        from: 46,
        to: 40,
        hint: "<b>Дорога</b><br/>Кёльн-Лилль<br/><br/>Качество: 0.99",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 35,
        type: "auto",
        from: 19,
        to: 40,
        hint: "<b>Дорога</b><br/>Копенгаген-Лилль<br/><br/>Качество: 0.98",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 37,
        type: "auto",
        from: 43,
        to: 19,
        hint: "<b>Дорога</b><br/>Берлин-Копенгаген<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 38,
        type: "auto",
        from: 16,
        to: 19,
        hint: "<b>Дорога</b><br/>Стокгольм-Копенгаген<br/><br/>Качество: 0.99",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 40,
        type: "auto",
        from: 17,
        to: 16,
        hint: "<b>Дорога</b><br/>Таллин-Стокгольм<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 42,
        type: "auto",
        from: 3,
        to: 6,
        hint: "<b>Дорога</b><br/>Москва-Смоленск<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 43,
        type: "auto",
        from: 29,
        to: 6,
        hint: "<b>Дорога</b><br/>Киев-Смоленск<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 44,
        type: "auto",
        from: 21,
        to: 6,
        hint: "<b>Дорога</b><br/>Минск-Смоленск<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 46,
        type: "auto",
        from: 29,
        to: 3,
        hint: "<b>Дорога</b><br/>Киев-Москва<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 47,
        type: "auto",
        from: 9,
        to: 3,
        hint: "<b>Дорога</b><br/>Воронеж-Москва<br/><br/>Качество: 0.99",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 48,
        type: "auto",
        from: 29,
        to: 9,
        hint: "<b>Дорога</b><br/>Киев-Воронеж<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 49,
        type: "auto",
        from: 27,
        to: 9,
        hint: "<b>Дорога</b><br/>Одесса-Воронеж<br/><br/>Качество: 0.97",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 50,
        type: "auto",
        from: 29,
        to: 27,
        hint: "<b>Дорога</b><br/>Киев-Одесса<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 51,
        type: "auto",
        from: 22,
        to: 27,
        hint: "<b>Дорога</b><br/>Братислава-Одесса<br/><br/>Качество: 0.97",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 52,
        type: "auto",
        from: 30,
        to: 27,
        hint: "<b>Дорога</b><br/>София-Одесса<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 53,
        type: "auto",
        from: 22,
        to: 30,
        hint: "<b>Дорога</b><br/>Братислава-София<br/><br/>Качество: 0.9700000000000001",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 54,
        type: "auto",
        from: 33,
        to: 30,
        hint: "<b>Дорога</b><br/>Любляна-София<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 55,
        type: "auto",
        from: 22,
        to: 33,
        hint: "<b>Дорога</b><br/>Братислава-Любляна<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 56,
        type: "auto",
        from: 24,
        to: 33,
        hint: "<b>Дорога</b><br/>Прага-Любляна<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 57,
        type: "auto",
        from: 45,
        to: 33,
        hint: "<b>Дорога</b><br/>Нюрнберг-Любляна<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 58,
        type: "auto",
        from: 46,
        to: 45,
        hint: "<b>Дорога</b><br/>Кёльн-Нюрнберг<br/><br/>Качество: 0.925",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 60,
        type: "auto",
        from: 43,
        to: 45,
        hint: "<b>Дорога</b><br/>Берлин-Нюрнберг<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 61,
        type: "auto",
        from: 24,
        to: 45,
        hint: "<b>Дорога</b><br/>Прага-Нюрнберг<br/><br/>Качество: 0.250001",
        weight: 0.5,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 62,
        type: "auto",
        from: 24,
        to: 43,
        hint: "<b>Дорога</b><br/>Прага-Берлин<br/><br/>Качество: 0.0500008",
        weight: 0.2,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 63,
        type: "auto",
        from: 23,
        to: 43,
        hint: "<b>Дорога</b><br/>Варшава-Берлин<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 67,
        type: "auto",
        from: 29,
        to: 21,
        hint: "<b>Дорога</b><br/>Киев-Минск<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 68,
        type: "auto",
        from: 23,
        to: 21,
        hint: "<b>Дорога</b><br/>Варшава-Минск<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 69,
        type: "auto",
        from: 22,
        to: 29,
        hint: "<b>Дорога</b><br/>Братислава-Киев<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 70,
        type: "auto",
        from: 23,
        to: 29,
        hint: "<b>Дорога</b><br/>Варшава-Киев<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 71,
        type: "auto",
        from: 24,
        to: 22,
        hint: "<b>Дорога</b><br/>Прага-Братислава<br/><br/>Качество: 0.94",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 72,
        type: "auto",
        from: 23,
        to: 22,
        hint: "<b>Дорога</b><br/>Варшава-Братислава<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 73,
        type: "auto",
        from: 23,
        to: 24,
        hint: "<b>Дорога</b><br/>Варшава-Прага<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 74,
        type: "auto",
        from: 43,
        to: 16,
        hint: "<b>Дорога</b><br/>Берлин-Стокгольм<br/><br/>Качество: 0.965",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 75,
        type: "auto",
        from: 21,
        to: 5,
        hint: "<b>Дорога</b><br/>Минск-Санкт-Петербург<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 78,
        type: "auto",
        from: 11,
        to: 8,
        hint: "<b>Дорога</b><br/>Сочи-Саратов<br/><br/>Качество: 0.98",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 84,
        type: "auto",
        from: 21,
        to: 16,
        hint: "<b>Дорога</b><br/>Минск-Стокгольм<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 86,
        type: "auto",
        from: 38,
        to: 41,
        hint: "<b>Дорога</b><br/>Париж-Ницца<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 90,
        type: "auto",
        from: 19,
        to: 46,
        hint: "<b>Дорога</b><br/>Копенгаген-Кёльн<br/><br/>Качество: 0.97",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 91,
        type: "auto",
        from: 43,
        to: 46,
        hint: "<b>Дорога</b><br/>Берлин-Кёльн<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 92,
        type: "auto",
        from: 41,
        to: 46,
        hint: "<b>Дорога</b><br/>Ницца-Кёльн<br/><br/>Качество: 0.995",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 96,
        type: "auto",
        from: 34,
        to: 33,
        hint: "<b>Дорога</b><br/>Тирана-Любляна<br/><br/>Качество: 0.975",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 107,
        type: "auto",
        from: 34,
        to: 30,
        hint: "<b>Дорога</b><br/>Тирана-София<br/><br/>Качество: 0.98",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 109,
        type: "auto",
        from: 21,
        to: 17,
        hint: "<b>Дорога</b><br/>Минск-Таллин<br/><br/>Качество: 1.0",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
    {
        id: 130,
        type: "auto",
        from: 16,
        to: 23,
        hint: "<b>Дорога</b><br/>Стокгольм-Варшава<br/><br/>Качество: 0.99",
        weight: 2.0,
        color: "#111111",
        points: "",
        olimpic: false,
    },
];
