name: schedule-calculator

on:
  schedule:
    - cron:  '55 6-18/2 * * *'

jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: '14'
          - run: echo "NOW=$(TZ="Europe/Moscow" date +'%Y-%m-%d-%H')" >> $GITHUB_ENV
          - run: cd ./scripts
          - run: npm run start
          - run: cp calculator.json ../data/${{ env.NOW }}.json
          - run: /bin/cp -rf calculator.json ../data/latest.json
          - name: Add & Commit
            uses: EndBug/add-and-commit@v9.1.3
            with:
                fetch: false
                message: 'Update calculator data at ${{ env.NOW }}'
